name: Django Screenshot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - run: nohup python manage.py runserver --settings=demo.settings 0.0.0.0:8000 &
    - run: sleep 10

    - name: screenshot
      uses: saadmk11/comment-website-screenshot@main
      with:
        upload_to: github_branch
        capture_changed_html_files: yes
        capture_urls: 'http://172.17.0.1:8000/, http://172.17.0.1:8000/admin/login/'
